export const EMAIL_CHANGED = 'EMAIL_CHANGED';
export const PASSWORD_CHANGED = 'PASSWORD_CHANGED';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAIL = 'LOGIN_USER_FAIL';
export const LOGOUT_USER = 'LOGOUT_USER';
export const AUTH_LOADING = 'AUTH_LOADING';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';

export const REGISTER_UPDATE = 'REGISTER_UPDATE';
export const LOGIN_UPDATE = 'LOGIN_UPDATE';
export const RESET_UUID = 'RESET_UUID';
export const GET_ERRORS = 'GET_ERRORS';
export const GET_MESSAGE = 'GET_MESSAGE';
export const REGISTER_ERRORS = 'REGISTER_ERRORS';
export const LOGIN_ERRORS = 'LOGIN_ERRORS';

// Location action types
export const GET_ALL_COUNTRIES = 'GET_ALL_COUNTRIES';
export const GET_ALL_STATES = 'GET_ALL_STATES';
export const GET_LGAS = 'GET_LGAS';

export const SWITCH_VIEW = 'SWITCH_VIEW';

//loadings
export const WALLET_LOADING = 'WALLET_LOADING';
export const CATEGORIES_LOADING = 'CATEGORIES_LOADING';
export const STAKE_LOADING = 'STAKE_LOADING';
export const GAMES_LOADING = 'GAMES_LOADING';
export const SINGLE_GAME_LOADING = 'SINGLE_GAME_LOADING';
export const NOTIFICATION_LOADING = 'NOTIFICATION_LOADING';
export const REGISTER_LOADING = 'REGISTER_LOADING';
export const SINGLE_NOTIFICATION_LOADING = 'SINGLE_NOTIFICATION_LOADING';
export const FUND_LOADING = 'FUND_LOADING';
export const WITHDRAW_LOADING = 'WITHDRAW_LOADING';
export const FRIEND_REQUEST_LOADING = 'FRIEND_REQUEST_LOADING';
export const FORGOT_PASSWORD_LOADING = 'FORGOT_PASSWORD_LOADING';
export const PROFILE_UPDATE_LOADING = 'PROFILE_UPDATE_LOADING';
export const CREATE_GAME_LOADING = 'CREATE_GAME_LOADING';
export const MY_SINGLE_GAME_LOADING = 'MY_SINGLE_GAME_LOADING';
export const PIN_LOADING = 'PIN_LOADING';
export const RESOLVE_BANK_ACCOUNT_LOADING = 'RESOLVE_BANK_ACCOUNT_LOADING';
export const CREATE_CHAT_LOADING = 'CREATE_CHAT_LOADING';
export const GET_CHAT_LOADING = 'GET_CHAT_LOADING';

// wallet
export const GET_WALLET = 'GET_WALLET';
export const GET_TRANSACTIONS = 'GET_TRANSACTIONS';

export const INITIALIZE_USER = 'INITIALIZE_USER';
export const GET_MY_PROFILE = 'GET_MY_PROFILE';

//categories
export const GET_CATEGORIES = 'GET_CATEGORIES';

//stakes
export const STAKE_UPDATE = 'STAKE_UPDATE';

//errors
export const STAKE_ERROR = 'STAKE_ERROR';

//Games
export const GET_GAMES = 'GET_GAMES';
export const GET_SINGLE_GAME = 'GET_SINGLE_GAME';
export const GET_MY_SINGLE_GAME = 'GET_MY_SINGLE_GAME';
export const GET_MY_GAMES = 'GET_MY_GAMES';
export const CREATE_GAME_ERROR_MESSAGE = 'CREATE_GAME_ERROR_MESSAGE';
export const GAME_UPDATE = 'GAME_UPDATE';
export const CREATE_GAME_UPDATE = 'CREATE_GAME_UPDATE';
export const CLEAR_GAME_DATA = 'CLEAR_GAME_DATA';

//notifications
export const GET_NOTIFICATION = 'GET_NOTIFICATION';
export const GET_SINGLE_NOTIFICATION = 'GET_SINGLE_NOTIFICATION';
export const IS_PUSH_NOTIFICATION = 'IS_PUSH_NOTIFICATION';
export const SET_PUSH_NOTIFICATION_DATA = 'SET_PUSH_NOTIFICATION_DATA';
export const HAS_RECEIVED_NOTIFICATION = 'HAS_RECEIVED_NOTIFICATION';

//friends
export const GET_FRIEND_REQUESTS = 'GET_FRIEND_REQUESTS';
export const GET_SINGLE_FRIEND_REQUEST = 'GET_SINGLE_FRIEND_REQUEST';
export const GET_USERS = 'GET_USERS';
export const GET_FRIENDS = 'GET_FRIENDS';
export const FRIEND_UPDATE = 'FRIEND_UPDATE';

//funding
export const FUND_UPDATE = 'FUND_UPDATE';
export const FUND_ERROR = 'FUND_ERROR';
export const WITHDRAW_ERROR = 'WITHDRAW_ERROR';
export const WITHDRAW_ERROR_MESSAGE = 'WITHDRAW_ERROR_MESSAGE';
export const REFERRAL_ERROR = 'REFERRAL_ERROR';
export const CREATE_GAME_ERROR = 'CREATE_GAME_ERROR';
export const GET_PAYPAL_FUNDING_DETAILS = 'GET_PAYPAL_FUNDING_DETAILS';
export const GET_PAYSTACK_FUNDING_DETAILS = 'GET_PAYSTACK_FUNDING_DETAILS';


// profile
export const PROFILE_UPDATE_ERROR = 'PROFILE_UPDATE_ERROR';
export const PROFILE_UPDATE_VALIDATION_ERROR = 'PROFILE_UPDATE_VALIDATION_ERROR';

// modals
export const TOGGLE_ADD_AMOUNT_MODAL = 'TOGGLE_ADD_AMOUNT_MODAL';
export const TOGGLE_WITHDRAW_MODAL = 'TOGGLE_WITHDRAW_MODAL';
export const TOGGLE_UPDATE_PROFILE_MODAL = 'TOGGLE_UPDATE_PROFILE_MODAL';
export const TOGGLE_IMAGE_VIEW_MODAL = 'TOGGLE_IMAGE_VIEW_MODAL';
export const SET_IMAGE_IN_MODAL = 'SET_IMAGE_IN_MODAL';
export const TOGGLE_FRIEND_REQUEST_MODAL = 'TOGGLE_FRIEND_REQUEST_MODAL';
export const SET_DATA_IN_FRIEND_REQUEST_MODAL = 'SET_DATA_IN_FRIEND_REQUEST_MODAL';
export const TOGGLE_CHANGE_PIN_MODAL = 'TOGGLE_CHANGE_PIN_MODAL';
export const TOGGLE_CREATE_PIN_MODAL = 'TOGGLE_CREATE_PIN_MODAL';

//password reset
export const FORGOT_PASSWORD_ERROR = 'FORGOT_PASSWORD_ERROR';
export const RESET_UPDATE = 'RESET_UPDATE';
export const RESET_PASSWORD_ERROR = 'RESET_PASSWORD_ERROR';
export const VALIDATE_TOKEN_LOADING = 'VALIDATE_TOKEN_LOADING';

//settings
export const UPDATE_SETTING_LOADING = 'UPDATE_SETTING_LOADING';
export const GET_SETTING = 'GET_SETTING';
export const SETTING_UPDATE = 'SETTING_UPDATE';

//error
export const CREATE_PIN_ERROR = 'CREATE_PIN_ERROR';
export const CREATE_PIN_ERROR_MESSAGE = 'CREATE_PIN_ERROR_MESSAGE'

//banks
export const GET_BANKS = 'GET_BANKS';

//chats
export const CHAT_UPDATE = 'CHAT_UPDATE';
export const CHAT_ERROR = 'CHAT_ERROR';
export const GET_CHAT = 'GET_CHAT';
export const APPEND_LAST_MESSAGE = 'APPEND_LAST_MESSAGE';