# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Probet' do
  pod 'AppCenterReactNativeShared', '~> 1.12.2'
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Probet

  

  platform :ios, '9.0'
  target 'ProbetTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'Probet-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Probet-tvOS

  target 'Probet-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
